name: WorldSkills Asia
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Setup
title:               WorldSkills Asia
description:         Improving our region through the power of skills
tagline:             Improving our region through the power of skills
url:
baseurl: "worldskillsasia"
logo:                /images/LOGO-RGB.png
tel:
email:               test@worldskillsasia.com

plugins:
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /images/LOGO-RGB.png
